name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.setup-matrix.outputs.matrix_json }}
    steps:
      - name: Generate random matrix
        id: setup-matrix
        run: |
          # Generate random number between 5-10
          loop_count=$((RANDOM % 6 + 5))
          
          # Create JSON array of sequence numbers
          seq_numbers=$(seq 0 $((loop_count - 1)) | tr '\n' ',' | sed 's/,$//')
          matrix_json="[$seq_numbers]"
          
          echo "matrix_json=$matrix_json" >> $GITHUB_OUTPUT
          echo "Generated matrix with $loop_count runs"

  generate:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        delay_step: ${{ fromJson(needs.setup.outputs.matrix_json) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add staggered delay
        run: |
          delay_seconds=$(( ${{ matrix.delay_step }} * 15 ))
          echo "Waiting for $delay_seconds seconds before running"
          sleep $delay_seconds

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#fa9630&color_dots=#161b22,#44365b,#654f83,#a884de,#cbaaff

      - name: Commit changes
        run: |
          git config --global user.email "ijlalahmad845@gmail.com"
          git config --global user.name "Ijlal Ahmad"
          git pull --rebase
          git add .
          git commit -m "Update snake animation (run ${{ matrix.delay_step }})"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
