name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    name: Generate snake animation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_dots=#161b22,#44365b,#654f83,#a884de,#cbaaff

      # Commit the changes
      - name: Commit
        run: |
          git config --global user.email "ijlalahmad845@gmail.com"
            git config --global user.name "Ijlal Ahmad"
            git add .
            git commit -m "update snake animation"
            git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
