name: generate animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # Allows manual execution
  workflow_dispatch:

  # Run on every push to the main branch
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      loop_count: ${{ steps.randomizer.outputs.loop_count }}

    steps:
      - name: Generate random loop count (5-10)
        id: randomizer
        run: echo "loop_count=$((RANDOM % 6 + 5))" >> $GITHUB_ENV

  generate:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        run_index: ${{ fromJson(format('[{0}]', join(',', range(1, env.loop_count | int)))) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#fa9630&color_dots=#161b22,#44365b,#654f83,#a884de,#cbaaff

      - name: Commit changes
        run: |
          git config --global user.email "ijlalahmad845@gmail.com"
          git config --global user.name "Ijlal Ahmad"
          git add .
          git commit -m "update snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
