name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.setup-matrix.outputs.matrix_json }}
    steps:
      - name: Generate even number of runs (4-10)
        id: setup-matrix
        run: |
          # Generate even number between 4-10
          loop_count=$(( (RANDOM % 4 + 2) * 2 ))
          
          # Create array of indices
          matrix_indices=$(seq 0 $((loop_count - 1)) | tr '\n' ',' | sed 's/,$//')
          echo "matrix_json=[$matrix_indices]" >> $GITHUB_OUTPUT
          echo "Generated $loop_count runs (indices: $matrix_indices)"

  generate:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        index: ${{ fromJson(needs.setup.outputs.matrix_json) }}
      max-parallel: 1  # Run jobs sequentially
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Delete snake file (even indices)
        if: ${{ matrix.index % 2 == 0 }}
        run: |
          rm -rf snake/ || true
          echo "Deleted snake directory"

      - name: Generate snake animation (odd indices)
        if: ${{ matrix.index % 2 != 0 }}
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#fa9630&color_dots=#161b22,#44365b,#654f83,#a884de,#cbaaff

      - name: Commit changes
        run: |
          git config --global user.email "ijlalahmad845@gmail.com"
          git config --global user.name "Ijlal Ahmad"
          git add .
          
          if [ $(( ${{ matrix.index }} % 2 )) -eq 0 ]; then
            commit_msg="Deleted snake animation (step ${{ matrix.index }})"
          else
            commit_msg="Generated snake animation (step ${{ matrix.index }})"
          fi
          
          git commit -m "$commit_msg" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
