name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.setup-matrix.outputs.matrix_json }}
    steps:
      - name: Generate even number of runs (4-10)
        id: setup-matrix
        run: |
          # Generate even number between 4-10
          loop_count=$(( (RANDOM % 4 + 2) * 2 ))
          
          # Create matrix with even/odd markers
          matrix_json="["
          for i in $(seq 0 $((loop_count - 1))); do
            if [ $((i % 2)) -eq 0 ]; then
              type="delete"
            else
              type="generate"
            fi
            matrix_json+="{\"index\":$i,\"operation\":\"$type\"},"
          done
          matrix_json="${matrix_json%,}]"
          
          echo "matrix_json=$matrix_json" >> $GITHUB_OUTPUT
          echo "Generated $loop_count runs"

  generate:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        config: ${{ fromJson(needs.setup.outputs.matrix_json) }}
      max-parallel: 1  # Sequential execution
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Delete snake folder
        if: ${{ matrix.config.operation == 'delete' }}
        run: |
          rm -rf snake/
          echo "Deleted snake directory"

      - name: Generate snake animation
        if: ${{ matrix.config.operation == 'generate' }}
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#fa9630&color_dots=#161b22,#44365b,#654f83,#a884de,#cbaaff

      - name: Commit changes
        run: |
          git config --global user.email "ijlalahmad845@gmail.com"
          git config --global user.name "Ijlal Ahmad"
          git add .
          
          if [ "${{ matrix.config.operation }}" = "delete" ]; then
            commit_msg="Deleted snake files (step ${{ matrix.config.index }})"
          else
            commit_msg="Generated snake animation (step ${{ matrix.config.index }})"
          fi
          
          git commit -m "$commit_msg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
